apiVersion: skaffold/v1beta2
kind: Config
build:
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
    - image: hello-jib
      context: .
      # To learn more about how Jib builds Java containers visit
      # https://github.com/GoogleContainerTools/jib
      jibMaven: {}
# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
profiles:
# use the cloudbuild profile to build images using Google Cloud Build
- name: cloudbuild
  build:
    googleCloudBuild: {}
# use the dockerfile profile to build images using Docker instead of Jib
- name: dockerfile
  build:
    tagPolicy:
      envTemplate:
        template: "{{.IMAGE_NAME}}:0.0.2-SNAPSHOT"
    artifacts:
      - image: hello-jib
        context: .
