apiVersion: skaffold/v1beta2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: hello-jib
      context: .
      jibMaven: {}
deploy:
  kubectl:
    manifests:
      - ./kubernetes-manifests/**.yaml
profiles:
  - name: cloudbuild
    build:
      googleCloudBuild: {}
  - name: dockerfile
    build:
      local:
        push: true
        useBuildkit: false
        useDockerCLI: false
      tagPolicy:
        envTemplate:
          template: '{{.IMAGE_NAME}}:0.0.2-SNAPSHOT'
      artifacts:
        - image: hello-jib
          context: .