apiVersion: apps/v1
kind: Deployment
metadata:
  name: heroes-v2
  namespace: heroes-ns
  labels:
    app: heroes
    version: v2
spec:
  selector:
    matchLabels:
      app: heroes
      version: v2
  replicas: 1
  template:
    metadata:
      labels:
        app: heroes
        version: v2
    spec:
      imagePullSecrets:
        - name: milocalregistry
      containers:
      - name: heroes
        image: misheroes
        imagePullPolicy: Always 
        ports:
        - containerPort: 8082
          name: http
          protocol: TCP
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
              port: 8082
              path: /heroes
          initialDelaySeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
              port: 8082
              path: /heroes
          initialDelaySeconds: 10
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: heroes-service
  namespace: heroes-ns
spec:
  type: NodePort
  selector:
    app: heroes
    version: v2
  ports:
  - port: 8082
    targetPort: 8082
    nodePort: 30150
