apiVersion: apps/v1
kind: Deployment
metadata:
  name: heroes-v2
  namespace: heroes-ns
  labels:
    app: heroes
    version: v2
spec:
  selector:
    matchLabels:
      app: heroes
      version: v2
  replicas: 1
  template:
    metadata:
      labels:
        app: heroes
        version: v2
    spec:
      imagePullSecrets:
        - name: milocalregistry
      containers:
      - name: heroes
        image: hello-jib:0.0.2-SNAPSHOT
        imagePullPolicy: Always 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8082
        livenessProbe:
          httpGet:
              port: "8082"
              path: /heroes
          initialDelaySeconds: 15
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
              port: "8082"
              path: /heroes
          initialDelaySeconds: 15
          timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: heroes-service
spec:
  type: ClusterIP
  selector:
    app: heroes
    version: v2
  ports:
  - port: 3000
    targetPort: 8082
